```{r}
library(ggplot2)
```

Here, we get the data from the csv and clean it up.
```{r}
 stateReg <- read.csv("Resources/10962-ev-registration-counts-by-state_9-06-24.csv", header=TRUE, sep =",")
 stateReg
```

Next, we create a bar plot with our counts.
```{r}
ggplot(stateReg, aes(x = State, y = Registration.Count / 1000)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(
    title = "Registration Counts Sorted Alphabetically",
    y = "Registrations (In Thousands)", 
    x = "State"
  ) +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90))
```

We see that California is a major outlier, so lets create a plot without it.
```{r}
withoutCali <- subset(stateReg, stateReg$State != "California")
withoutCali


ggplot(withoutCali, aes(x = State, y = Registration.Count / 1000)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(
    title = "Registration Counts Sorted Alphabetically (Without California)",
    y = "Registrations (In Thousands)", 
    x = "State"
  ) +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90))
```

Let's look at the data sorted by the count.
```{r}
sortedStates <- stateReg[order(stateReg$Registration.Count, decreasing = TRUE), ]
sortedStates
```

Let's look at the five number summary of our data and the total count.
```{r}
summary(stateReg)
sum(stateReg$Registration.Count)
```